# Generated by Django 3.2.19 on 2025-04-26 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_remove_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='movies/'),
            preserve_default=False,
        ),
    ]
